import { Card, CardContent } from "@/components/ui/card";
import { ArrowLeft, Check, Clock, TrendingUp } from "lucide-react";
import Link from "next/link";
import AnimatedSection from "@/components/animated-section";
import ContactSection from "@/components/contact-section";
import FAQSection from "@/components/faq-section";
import QuoteSection from "@/components/quote-section";
import { BASE_URL } from "@/lib/jsonld";
import type { Metadata } from "next";

function normalizeLocation(value?: string) {
  if (!value) return undefined;
  const spaced = value.replace(/-/g, " ");
  return spaced
    .split(" ")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

const serviceData = {
  title: "ChatGPT Advertising",
  subtitle: "Position your brand in the answers of the world's most used AI",
  description:
    "Capture high-intent traffic with native ads on ChatGPT (SearchGPT). Position your brand in conversational search answers exactly when decisions are made.",
  gradient: "from-[#10a37f] to-[#007aff]", // ChatGPT Green to Blue
  price: "From $1500/month + ad budget",
  duration: "Setup: 2-3 weeks",
  features: [
    "Native ads on ChatGPT (SearchGPT)",
    "Contextual sponsored answers",
    "Generative Engine Optimization (GEO)",
    "Brand citation as authoritative source",
    "Conversational intent segmentation",
    "Visual formats in chat",
    "AI Visibility Reports",
  ],
  process: [
    {
      title: "AI Audit",
      description: "We analyze how ChatGPT currently perceives and cites your brand",
    },
    {
      title: "Configuration",
      description: "We prepare your assets and connect to the OpenAI ad network",
    },
    {
      title: "Content Optimization",
      description: "We adapt your web to be the AI's preferred source",
    },
    {
      title: "Launch and Adjustment",
      description: "We activate ads and refine based on real queries",
    },
  ],
  benefits: [
    "Exclusive access to ChatGPT users",
    "Higher conversion rate than traditional search",
    "Unsaturated market (Being new, there is very little competition)",
    "Positioning as authority in your industry",
  ],
};

const faqs = [
  {
    question: "What is advertising on ChatGPT?",
    answer:
      "It is a new way to advertise where your brand appears recommended within the answers generated by ChatGPT. It uses SearchGPT technology to show your link or product exactly when the user asks about related topics, integrating naturally into the conversation.",
  },
  {
    question: "Is it the same as Google Ads?",
    answer:
      "No. While Google Ads is based on keyword auctions, advertising on ChatGPT is based on intent and chat context. You capture the user when they are investigating or looking for a complex solution, offering a direct answer instead of a list of blue links.",
  },
  {
    question: "Where do my ads appear?",
    answer:
      "Your ads appear within the ChatGPT chat interface, specifically when the AI queries the web (SearchGPT) to answer. They can be seen as source citations, product suggestions, or highlighted links within the answer.",
  },
];

export async function generateMetadata({
  searchParams,
}: {
  searchParams?: { [key: string]: string | string[] | undefined };
}): Promise<Metadata> {
  const raw = searchParams?.Location;
  const slug = Array.isArray(raw) ? raw[0] : raw;
  const location = normalizeLocation(slug);
  const slugPart = slug ? `-${slug}` : "";
  const canonical = `${BASE_URL}/services/chatgpt-ads${slugPart}`;
  const canonicalEn = `${BASE_URL}/services/chatgpt-ads${slugPart}`;

  return {
    title: {
      default: `${serviceData.title}${location ? ` - ${location}` : ""}`,
      template: "%s | North Blue Agency",
    },
    description: serviceData.description,
    alternates: {
      canonical,
      languages: { es: canonical, en: canonicalEn },
    },
    keywords: [
      "chatgpt advertising",
      "searchgpt ads",
      "ai ads",
      "marketing on chatgpt",
      "geo optimization",
      "generative engine optimization",
      "conversational advertising",
      "North Blue Agency",
    ],
    openGraph: {
      title: `${serviceData.title}${
        location ? ` - ${location}` : ""
      } - North Blue Agency`,
      description: serviceData.description,
      url: canonical,
      type: "website",
      images: [
        {
          url: `${BASE_URL}/images/og/services-chatgpt-ads.png`,
          alt: `${serviceData.title} - North Blue Agency`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `${serviceData.title} - North Blue Agency`,
      description: serviceData.description,
      images: [`${BASE_URL}/images/og/services-chatgpt-ads.png`],
    },
    publisher: "North Blue Agency",
  };
}

export default function ChatgptAdsPage({
  searchParams,
}: {
  searchParams?: { [key: string]: string | string[] | undefined };
}) {
  const raw = searchParams?.Location;
  const slug = Array.isArray(raw) ? raw[0] : raw;
  const locationText = normalizeLocation(slug);
  return (
    <>
      <div className="min-h-screen">
        {/* Hero Section */}
        <div className="py-10 bg-gradient-to-br from-gray-900 via-gray-800 to-black"></div>
        <section
          className={`py-20 bg-gradient-to-br from-[#0f172a] to-[#1e293b] text-white relative overflow-hidden`}
        >
          {/* Custom background for AI theme */}
           <div className="absolute inset-0 opacity-30">
            <div className={`absolute top-0 right-0 w-full h-full bg-gradient-to-bl ${serviceData.gradient} opacity-20`}></div>
           </div>

          <div className="absolute inset-0">
             {/* Techy looking circles */}
            <div className="absolute top-20 left-10 w-72 h-72 bg-[#10a37f]/20 rounded-full blur-3xl animate-pulse"></div>
            <div className="absolute bottom-20 right-10 w-96 h-96 bg-[#007aff]/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
          </div>

          <div className="container mx-auto px-4 relative z-10">
            <AnimatedSection>
              <Link
                href="/services"
                className="inline-flex items-center text-white/80 hover:text-white mb-6 transition-colors"
              >
                <ArrowLeft size={20} className="mr-2" />
                Back to services
              </Link>

              <h1 className="text-5xl md:text-6xl font-bold mb-6">
                {serviceData.title}
                {locationText ? ` - ${locationText}` : ""}
              </h1>
              <p className="text-xl md:text-2xl text-white/90 max-w-3xl mb-8">
                {serviceData.subtitle}
              </p>

              <div className="flex flex-col sm:flex-row gap-4">
                <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-lg px-6 py-3">
                  <div className="flex items-center space-x-2">
                    <Clock size={20} className="text-[#10a37f]" />
                    <span className="font-semibold">
                      {serviceData.duration}
                    </span>
                  </div>
                </div>
                <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-lg px-6 py-3">
                  <div className="flex items-center space-x-2">
                    <TrendingUp size={20} className="text-[#007aff]" />
                    <span className="font-semibold">{serviceData.price}</span>
                  </div>
                </div>
              </div>
            </AnimatedSection>
          </div>
        </section>

        {/* Description Section */}
        <section className="py-20 bg-white">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              <AnimatedSection animation="fadeInLeft">
                <h2 className="text-3xl md:text-4xl font-bold mb-6">
                  Why advertise on ChatGPT?
                </h2>
                <p className="text-lg text-gray-600 leading-relaxed mb-8">
                  {serviceData.description}
                </p>

                <div className="space-y-4">
                  {serviceData.benefits.map(
                    (benefit: string, index: number) => (
                      <div key={index} className="flex items-center space-x-3">
                        <div className={`w-6 h-6 bg-gradient-to-r ${serviceData.gradient} rounded-full flex items-center justify-center flex-shrink-0`}>
                          <Check className="text-white" size={14} />
                        </div>
                        <span className="text-gray-700">{benefit}</span>
                      </div>
                    )
                  )}
                </div>
              </AnimatedSection>

              <AnimatedSection animation="fadeInRight" delay={200}>
                <Card className="border-0 shadow-2xl overflow-hidden">
                  <div className={`h-2 w-full bg-gradient-to-r ${serviceData.gradient}`}></div>
                  <CardContent className="p-8">
                    <h3 className="text-2xl font-bold mb-6">
                      Service Features
                    </h3>
                    <div className="space-y-4">
                      {serviceData.features.map(
                        (feature: string, index: number) => (
                          <div
                            key={index}
                            className="flex items-start space-x-3"
                          >
                            <div className="w-5 h-5 bg-[#10a37f] rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                              <Check className="text-white" size={12} />
                            </div>
                            <span className="text-gray-700">{feature}</span>
                          </div>
                        )
                      )}
                    </div>
                  </CardContent>
                </Card>
              </AnimatedSection>
            </div>
          </div>
        </section>

        {/* Process Section */}
        <section className="py-20 bg-gray-50">
          <div className="container mx-auto px-4">
            <AnimatedSection className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6">
                Strategy for Generative Engines
              </h2>
              <p className="text-lg text-gray-600 max-w-2xl mx-auto">
                It's not traditional SEO. It's optimization to be the answer the AI chooses.
              </p>
            </AnimatedSection>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              {serviceData.process.map((step: any, index: number) => (
                <AnimatedSection key={index} delay={index * 100}>
                  <Card className="text-center border-0 shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-1 h-56">
                    <CardContent className="p-6">
                      <div className={`w-12 h-12 bg-gradient-to-r ${serviceData.gradient} rounded-full flex items-center justify-center mx-auto mb-4`}>
                        <span className="text-white font-bold">
                          {index + 1}
                        </span>
                      </div>
                      <h3 className="text-lg font-bold mb-3">{step.title}</h3>
                      <p className="text-gray-600 max-w-[250px] mx-auto text-sm">
                        {step.description}
                      </p>
                    </CardContent>
                  </Card>
                </AnimatedSection>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <FAQSection
          title={`Frequently Asked Questions`}
          faqs={faqs}
        />

        {/* CTA Section */}
        <QuoteSection
          title="Be the first on ChatGPT"
          subtitle="The competition hasn't arrived yet. Position yourself as a leader in the new search era."
          buttonText="Talk to an AI expert"
        />

        {/* Contact Section */}
        <ContactSection />
      </div>
    </>
  );
}
